name: Markdown Quality Checks

on: [push]

jobs:
  quality:
    name: Markdown Quality Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: |
            **/*.md
            !**/.venv/**
            !**/node_modules/**
